### ISSUE TITLE
Authentication of users

### ISSUE THREAD

**Issue by loffa** [TMEIT/website#2]
Implementation of user authentication and registration using API.

Suggestions is:

- KTH Autj
- Google auth
- Username/password

**Comment by JustinLex** [comment]
Google authentication is implemented now as of PR#12.
The next step here is to figure out how to handle KTH SAML tokens and set up a registration form.

**Comment by JustinLex** [comment]
We're now using email+password, KTH integration is hard and not useful. See: [https://github.com/TMEIT/website/issues/33#issuecomment-566406327](https://github.com/TMEIT/website/issues/33#issuecomment-566406327) Google integration shouldn't be the primary option either because Google.

Initial implementation is on the backend-2020 branch as of this commit: https://github.com/TMEIT/website/issues/33#issuecomment-566406327

**Comment by JustinLex** [comment]
Done
